version: '3.1'

services:
  redis:
    image: redis:5-alpine
    container_name: redis
    restart: always
    ports:
      - 127.0.0.1:6379:6379
  peer-calls:
    image: peer-calls
    build: ./
    restart: unless-stopped
    container_name: peer-calls
    volumes:
      - ./config:/app/config
      - ./.cert/:/app/.cert
    ports:
      - 3100:3000
